/* MI-1a — the committed SQL files, run in a REAL Postgres against a fixture with the live shape of
   monthly_sales (both bigint and uuid ids; production is uuid). Uses supabase/mi1a_*.sql exactly as
   committed, so what is tested is what Angelo runs.
   Needs psql and a server; skipped when there is none.
     PGTEST_PSQL=/usr/lib/postgresql/16/bin/psql PGHOST=/var/tmp/pgmi PGPORT=55433 PGUSER=postgres node test/mi1a-identity.pg.test.js */
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const assert = require('assert');

const PSQL = process.env.PGTEST_PSQL || 'psql';
const SUP = f => path.join(__dirname, '..', 'supabase', f);
const FIX = path.join(__dirname, 'mi1a', 'fixture.sql');
const CHECKS = path.join(__dirname, 'mi1a', 'checks.sql');
const run = (db, sql) => { const r = spawnSync(PSQL, ['-X', '-q', '-A', '-t', '-v', 'ON_ERROR_STOP=1', '-d', db, '-c', sql], { encoding: 'utf8' });
  if (r.error || r.status !== 0) throw new Error((r.error && r.error.message) || r.stderr || ('psql exit ' + r.status)); return r.stdout.trim(); };
const file = (db, f) => { const r = spawnSync(PSQL, ['-X', '-q', '-v', 'ON_ERROR_STOP=1', '-d', db, '-f', f], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(r.stderr); return (r.stdout || '') + (r.stderr || ''); };
const fileRaw = (db, f) => spawnSync(PSQL, ['-X', '-q', '-v', 'ON_ERROR_STOP=1', '-d', db, '-f', f], { encoding: 'utf8' });
try { run('postgres', 'select 1'); } catch (e) { console.log('SKIP: no Postgres (' + String(e.message).split('\n')[0] + ')'); process.exit(0); }

let pass = 0, fail = 0;
function t(name, fn) { try { fn(); pass++; console.log('  ok   ' + name); } catch (e) { fail++; console.log('  FAIL ' + name + '\n       ' + (e && e.message || e).toString().split('\n')[0]); } }
const SNAP = `select md5(string_agg(concat_ws('|',id,manufacturer,source,period,dealer_id,amount,commission,external_ref,source_file,customer_ref),';' order by id::text)) from monthly_sales`;
const tmp = (name, text) => { const p = path.join(require('os').tmpdir(), 'mi1a-' + process.pid + '-' + name + '.sql'); fs.writeFileSync(p, text); return p; };
const fixtureFor = idType => idType === 'uuid'
  ? tmp('fx-uuid', fs.readFileSync(FIX, 'utf8').replace('id bigint generated by default as identity primary key,', 'id uuid primary key default gen_random_uuid(),'))
  : FIX;
function fresh(db, idType, steps) {
  run('postgres', `drop database if exists ${db}`); run('postgres', `create database ${db}`);
  file(db, fixtureFor(idType)); for (const s of steps) file(db, SUP(s));
}

for (const idType of ['bigint', 'uuid']) {
  const DB = `mi1a_${idType}_${process.pid}`;
  console.log(`\n— monthly_sales.id ${idType} —`);
  try {
    t('Part 0 snapshot copies the table and refuses a second snapshot', () => {
      fresh(DB, idType, []);
      const before = run(DB, 'select count(*) from monthly_sales');
      file(DB, SUP('mi1a_part0_snapshot.sql'));
      assert.strictEqual(run(DB, 'select count(*) from mi1a_snapshot_monthly_sales'), before);
      assert.strictEqual(fileRaw(DB, SUP('mi1a_part0_snapshot.sql')).status !== 0, true, 'second snapshot refused');
    });
    t('Part 1 is additive (no row changes) and safe to re-run', () => {
      const before = run(DB, SNAP);
      file(DB, SUP('mi1a_part1_schema.sql')); file(DB, SUP('mi1a_part1_schema.sql'));
      assert.strictEqual(run(DB, SNAP), before);
      assert.strictEqual(run(DB, 'select count(*) from mi1a_enrollment'), '0', 'Part 1 enrols nothing');
    });
    t('after Part 1 (nothing enrolled), old-style writes for every manufacturer still work', () => {
      run(DB, `insert into monthly_sales(manufacturer,period,amount,source,external_ref) values ('pedifix','2026-10-01',1,'sales_report','pedifix|t|0'),('strongback-mobility','2026-10-01',1,'sales_report','strongback-mobility|t|X|0')`);
      run(DB, `delete from monthly_sales where external_ref in ('pedifix|t|0','strongback-mobility|t|X|0')`);
      run(DB, `insert into monthly_sales(manufacturer,period,amount,commission,source) values ('pedifix','2026-10-01',1,1,'commission')`);
      run(DB, `delete from monthly_sales where manufacturer='pedifix' and period='2026-10-01' and source='commission'`);
    });
    t('dry-run keys equal the keys Part 2 writes', () => {
      const dry = fs.readFileSync(SUP('mi1a_dryrun_readonly.sql'), 'utf8');
      const i = dry.indexOf('-- D5.'); const j = dry.indexOf('select id, period', i);
      const cte = dry.slice(i, j).split('\n').slice(1).join('\n');
      const proposed = run(DB, cte + ` select string_agg(id::text||'='||new_external_ref, ',' order by id::text) from mi1a_proposed where manufacturer='strongback-mobility'`);
      file(DB, SUP('mi1a_part2_rekey_strongback.sql'));
      const written = run(DB, `select string_agg(id::text||'='||external_ref, ',' order by id::text) from monthly_sales where manufacturer='strongback-mobility' and source='sales_report'`);
      assert.strictEqual(written, proposed);
      assert.strictEqual(run(DB, `select manufacturer||'/'||lane from mi1a_enrollment`), 'strongback-mobility/sales_report');
    });
    t('behaviour checks (test/mi1a/checks.sql) all pass', () => {
      const out = file(DB, CHECKS);
      const ok = (out.match(/ok {3}/g) || []).length;
      assert.ok(!/ERROR|FAIL/.test(out), out.split('\n').find(l => /ERROR|FAIL/.test(l)));
      assert.strictEqual(ok, 36, 'expected 36 checks, saw ' + ok);
    });
    t('rollback: old-style write refused before R1, accepted after R1+R2', () => {
      assert.throws(() => run(DB, `insert into monthly_sales(manufacturer,period,amount,source,external_ref) values ('strongback-mobility','2026-08-01',10,'sales_report','strongback-mobility|9999|X|0')`), /mi1a_write_guard/);
      file(DB, SUP('mi1a_rollback.sql'));
      run(DB, `insert into monthly_sales(manufacturer,period,amount,source,external_ref) values ('strongback-mobility','2026-08-01',10,'sales_report','strongback-mobility|9999|X|0')`);
      assert.strictEqual(run(DB, `select count(*) from monthly_sales where external_ref like '%|v2|%'`), '0');
    });
    t('full cycle (Part 0 → 1 → 2 → rollback) returns the table byte-identical', () => {
      fresh(DB, idType, []); const before = run(DB, SNAP);
      for (const f of ['mi1a_part0_snapshot.sql', 'mi1a_part1_schema.sql', 'mi1a_part2_rekey_strongback.sql', 'mi1a_rollback.sql']) file(DB, SUP(f));
      assert.strictEqual(run(DB, SNAP), before);
    });
    t('re-key aborts (nothing changed) if any total would move, a key collides, or coverage is partial', () => {
      fresh(DB, idType, ['mi1a_part1_schema.sql']); const before = run(DB, SNAP);
      const src = fs.readFileSync(SUP('mi1a_part2_rekey_strongback.sql'), 'utf8');
      const muts = [
        ["external_ref = 'strongback-mobility|v2|' || n.k_order", "amount = m.amount + 1, external_ref = 'strongback-mobility|v2|' || n.k_order"],
        ["|| n.k_sku || '|' || n.k_n\n", "|| 'X'\n"],
        ["where manufacturer = 'strongback-mobility' and source = 'sales_report'\n), n as", "where manufacturer = 'strongback-mobility' and source = 'sales_report' and amount > 0\n), n as"],
      ];
      for (const [from, to] of muts) {
        assert.ok(src.includes(from), 'anchor ' + from);
        const r = fileRaw(DB, tmp('mut', src.split(from).join(to)));
        assert.notStrictEqual(r.status, 0, 'mutant should abort: ' + from);
        assert.strictEqual(run(DB, SNAP), before, 'nothing changed: ' + from);
        assert.strictEqual(run(DB, 'select count(*) from mi1a_enrollment'), '0');
      }
    });
    t('re-key refuses when Strongback reuses an invoice number (identity audit gate)', () => {
      fresh(DB, idType, ['mi1a_part1_schema.sql']);
      run(DB, `update monthly_sales set order_date='2025-03-01' where invoice_no='6491' and product_code='Brochure Trifold'`);
      const before = run(DB, SNAP);
      const r = fileRaw(DB, SUP('mi1a_part2_rekey_strongback.sql'));
      assert.notStrictEqual(r.status, 0); assert.ok(/invoice numbers shared/.test(r.stderr));
      assert.strictEqual(run(DB, SNAP), before);
    });
  } finally { try { run('postgres', `drop database if exists ${DB}`); } catch (e) {} }
}

// AirAvant/BongoRx duplicate: correction and its rollback, against rows shaped like the two live ones.
{
  const DB = `mi1a_aa_${process.pid}`;
  console.log('\n— AirAvant duplicate correction —');
  try {
    fresh(DB, 'uuid', ['mi1a_part1_schema.sql']);
    run(DB, `insert into manufacturers values ('airavant-bongorx','AirAvant') on conflict do nothing;
      insert into monthly_sales(id,manufacturer,period,order_date,qty,amount,commission,customer_name,customer_ref,dealer_id,source,source_file,item_no,line_type,channel) values
       ('f6b9b070-e8fb-4cd5-9144-6d7fa9fa42f5','airavant-bongorx','2026-06-01','2026-06-03',10,1290,193.50,'Williams Bros. Healthcare Pharmacy','5917','00000000-0000-0000-0000-00000000000a','commission','BongoRx_Commission_Report_June_2026.xlsx','BNG500','INVOICE','physical'),
       ('39bec586-8464-48cd-85b4-f4799ca123e7','airavant-bongorx','2026-07-01','2026-07-02',20,2380,357.00,'X',null,null,'commission','BongoRx_Commission_Report_July_2026.xlsx','BNG500','INVOICE','dropship');
      insert into monthly_sales(id,manufacturer,period,order_date,invoice_no,product_code,product_name,qty,amount,commission,commission_rate,customer_name,dealer_id,source,source_file,external_ref,line_type,rep_name) values
       ('b09d0e04-232e-4fd1-bb38-14235ad58a91','airavant-bongorx','2026-06-01','2026-06-03','5917','BNG500','BNG500',10,1290,193.50,0.15,'Williams Bros. Healthcare Pharmacy','00000000-0000-0000-0000-00000000000a','sales_report','bongo commission report June 2026 team.pdf','airavant-bongorx|5917|BNG500|0','sale','Angelo Audia');`);
    const before = run(DB, SNAP);
    t('correction archives the PDF row whole and leaves the reviewed totals (2 rows, $3,670, $550.50)', () => {
      file(DB, SUP('mi1a_airavant_duplicate_correction.sql'));
      assert.strictEqual(run(DB, `select count(*)||'/'||sum(amount)||'/'||sum(commission) from monthly_sales where manufacturer='airavant-bongorx'`), '2/3670/550.50');
      assert.strictEqual(run(DB, `select row_data->>'source_file' from monthly_sales_superseded where sales_row_id='b09d0e04-232e-4fd1-bb38-14235ad58a91'`), 'bongo commission report June 2026 team.pdf');
      assert.strictEqual(run(DB, `select count(*) from monthly_sales where id='f6b9b070-e8fb-4cd5-9144-6d7fa9fa42f5'`), '1', 'statement row kept');
    });
    t('running the correction twice is refused (nothing changes)', () => {
      const mid = run(DB, SNAP);
      assert.notStrictEqual(fileRaw(DB, SUP('mi1a_airavant_duplicate_correction.sql')).status, 0);
      assert.strictEqual(run(DB, SNAP), mid);
    });
    t('rollback puts the row back exactly', () => {
      file(DB, SUP('mi1a_airavant_duplicate_correction_rollback.sql'));
      assert.strictEqual(run(DB, SNAP), before);
    });
    t('correction refuses if the rows changed since review', () => {
      run(DB, `update monthly_sales set amount=1291 where id='b09d0e04-232e-4fd1-bb38-14235ad58a91'`);
      const changed = run(DB, SNAP);
      assert.notStrictEqual(fileRaw(DB, SUP('mi1a_airavant_duplicate_correction.sql')).status, 0);
      assert.strictEqual(run(DB, SNAP), changed);
    });
  } finally { try { run('postgres', `drop database if exists ${DB}`); } catch (e) {} }
}

console.log(`\nmi1a-identity.pg: ${pass} passed, ${fail} failed`);
process.exitCode = fail ? 1 : 0;
