/* Phase 0 mutants: each undoes ONE protection, in memory only. phase0.mutants.js runs both
   Phase 0 suites against each and requires at least one test to fail — a mutant that survives
   means that protection is untested. */
module.exports = {
  'settings: no allowlist':            { file: 'routes-api.js', from: 'if(!rule) return json(403,{error:"That setting isn\'t available here."});', to: 'if(!rule) return json(200,{ok:true,value:((await sbGet(`app_settings?key=eq.${encodeURIComponent(key)}&select=value`).catch(()=>[]))[0]||{}).value||null});' },
  'settings: whole row returned':      { file: 'routes-api.js', from: 'value:v?pickFields(v,rule.fields):null', to: 'value:v' },
  'settings: any key writable':        { file: 'routes-api.js', from: 'if(!rule||!rule.writable) return json(403', to: 'if(false) return json(403' },
  'routes: dealer guard off':          { file: 'routes-api.js', from: 'if(off.length) return json(403,{error:"Not your dealer",dealer_ids:off});', to: '' },
  'routes: route grant grants all':    { file: 'routes-api.js', from: 'return off.filter(id=>!onMine.has(id));', to: 'return [];' },
  'routes: no route grant':            { file: 'routes-api.js', from: 'return off.filter(id=>!onMine.has(id));', to: 'return off;' },
  'routes: fake route id accepted':    { file: 'routes-api.js', from: 'if(!r) return {ok:false,status:404,error:"route not found"};', to: 'if(!r) return {ok:true,route:{}};' },
  'routes: dealer need not be a stop': { file: 'routes-api.js', from: 'if(!onRoute && !SC.seesAllDealers(me))', to: 'if(false)' },
  'geocode: fails open':               { file: 'geocode-api.js', from: 'if(need && safeEq(got,need))', to: 'if(!need || safeEq(got,need))' },
  'territory: fails open':             { file: 'territory-api.js', from: 'if(need && safeEq(got,need))', to: 'if(!need || safeEq(got,need))' },
  'ordering dealers-api: fails open':  { file: 'dealers-api.js', ordering: true, from: 'if(!need || got.length', to: 'if(need && got.length' },
  'ordering home-api: fails open':     { file: 'home-api.js', ordering: true, from: 'if(!need || got.length', to: 'if(need && got.length' },
  'staff: anyone bootstraps':          { file: 'staff-auth.js', from: 'const mayBootstrap = !staff && empty && !!boot && email===boot;', to: 'const mayBootstrap = !staff && empty;' },
  'staff: first sign-in sets password':{ file: 'staff-auth.js', from: 'const g=await tokenGrant(email,password);\n      if(!g.ok) return json(200,{ok:false,message:"Incorrect email or password.', to: 'let g=await tokenGrant(email,password);\n      if(!g.ok && staff){ await adminCreateUser(email,password); g=await tokenGrant(email,password); }\n      if(!g.ok) return json(200,{ok:false,message:"Incorrect email or password.' },
  'staff: no invite on add':           { file: 'staff-auth.js', from: 'try{ invite=await sendStaffLink(email,"invite"); }', to: 'try{ invite={ok:true}; }' },
  'staff: reset uses client redirect': { file: 'password-reset.js', from: 'body: JSON.stringify({ type: "recovery", email, options: { redirect_to } }),', to: 'body: JSON.stringify({ type: "recovery", email, options: { redirect_to: "https://evil.test/steal" } }),' },
  'email: dealer timeline open':       { file: 'email-sync-api.js', from: 'if(!(await SC.canAccessDealer(me,id,sbGet))) return json(403,{error:"Not your dealer"});', to: '' },
  'email: any message body':           { file: 'email-sync-api.js', from: 'if(!ownBox && !ownDealer) return json(403', to: 'if(false) return json(403' },
  'email: send onto any dealer':       { file: 'email-sync-api.js', from: 'if(dealerId && !(await SC.canAccessDealer(me,dealerId,sbGet))) return json(403', to: 'if(false) return json(403' },
  'tasks: any id':                     { file: 'crm-api.js', from: 'const own=await SC.authorizeRecord(me,"dealer_tasks",b.id,sbGet,{ownerFields:["assigned_rep"]});', to: 'const own={ok:true};' },
  'scope: owner field ignored':        { file: '_scope.js', from: 'if((myEmail && v===myEmail) || (myRep && v===myRep)) return {ok:true,row};', to: '' },
  'scope: dealer mismatch ignored':    { file: '_scope.js', from: 'return {ok:false,status:403,error:"That record doesn\'t belong to this dealer."};', to: '{}' },
  'contacts: any id':                  { file: 'crm-api.js', from: 'const own=await SC.authorizeRecord(me,"dealer_contacts",id,sbGet,{dealerId:b.dealer_id});\n        if(!own.ok) return json(own.status,{error:own.error});\n        try{ await sbSend("PATCH",`dealer_contacts?id=eq.${encodeURIComponent(id)}&dealer_id=eq.${encodeURIComponent(b.dealer_id)}`', to: 'try{ await sbSend("PATCH",`dealer_contacts?id=eq.${encodeURIComponent(id)}`' },
  'pipeline: add anywhere':            { file: 'pipeline-api.js', from: 'if(b.dealer_id && !(await SC.canAccessDealer(me,b.dealer_id,sbGet))) return json(403', to: 'if(false) return json(403' },
  'pipeline: update any deal':         { file: 'pipeline-api.js', from: 'const own=await SC.authorizeRecord(me,"opportunities",b.id,sbGet,{ownerFields:["owner_rep"]});', to: 'const own={ok:true};' },
  'pipeline: rep sets owner':          { file: 'pipeline-api.js', from: 'if(b.owner_rep!=null && manages)', to: 'if(b.owner_rep!=null)' },
  'pipeline: blank name matches':      { file: 'pipeline-api.js', from: 'oppList.filter(o=>!!myRep && ', to: 'oppList.filter(o=>' },
  'schedule: any request id':          { file: 'schedule-api.js', from: 'if (req0 && !canWork(req0)) return json(403', to: 'if (false) return json(403' },
  'schedule: whole queue':             { file: 'schedule-api.js', from: '.catch(() => [])).filter(canWork);', to: '.catch(() => []));' },
  'schedule: book others':             { file: 'schedule-api.js', from: 'if (!manages && repEmail.toLowerCase() !== myEmail) return json(403', to: 'if (false) return json(403' },
  'sales import: anyone':              { file: 'sales-import-api.js', from: 'if(!["president","admin","owner"].includes(String(me.role||"").toLowerCase())) return json(403', to: 'if(false) return json(403' },
  'platform: anyone sets mode':        { file: 'platform-api.js', from: 'if(!MGMT) return json(403', to: 'if(false) return json(403' },
  'audiences: reps allowed':           { file: 'audiences-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'campaigns: reps allowed':           { file: 'campaign-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'cardchamp: reps allowed':           { file: 'partner-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'dealer mgr: portal access open':    { file: 'dealers-api.js', from: 'if(!seesAll && !(await ownsDealer(me,b.dealer_id))) return json(403,{error:"Not your dealer"});\n        const r=await computeDealerAccess', to: 'const r=await computeDealerAccess' },
  'orders: blank name sees all':       { file: 'orders-admin.js', from: 'list=rn?list.filter(o=>String(o.rep||"").toLowerCase()===rn):[];', to: 'list=rn?list.filter(o=>String(o.rep||"").toLowerCase()===rn):list;' },
  'health: blank name sees unassigned':{ file: 'health-api.js', from: 'rows.filter(r=>!!rn && ', to: 'rows.filter(r=>' },
  'analytics: contact details leak':   { file: 'analytics.js', from: 'for (const nm of Object.keys(dealerInfo)) if (!mine.has(nm)) delete dealerInfo[nm];', to: '' },
};
