/* Phase 0 mutants: each undoes ONE protection, in memory only. phase0.mutants.js runs both
   Phase 0 suites against each and requires at least one test to fail — a mutant that survives
   means that protection is untested. */
module.exports = {
  'settings: no allowlist':            { file: 'routes-api.js', from: 'if(!rule) return json(403,{error:"That setting isn\'t available here."});', to: 'if(!rule) return json(200,{ok:true,value:((await sbGet(`app_settings?key=eq.${encodeURIComponent(key)}&select=value`).catch(()=>[]))[0]||{}).value||null});' },
  'settings: whole row returned':      { file: 'routes-api.js', from: 'value:v?pickFields(v,rule.fields):null', to: 'value:v' },
  'settings: any key writable':        { file: 'routes-api.js', from: 'if(!rule||!rule.writable) return json(403', to: 'if(false) return json(403' },
  'routes: dealer guard off':          { file: 'routes-api.js', from: 'if(off.length) return json(403,{error:"Not your dealer",dealer_ids:off});', to: '' },
  'routes: route grant grants all':    { file: 'routes-api.js', from: 'return off.filter(id=>!onMine.has(id));', to: 'return [];' },
  'routes: no route grant':            { file: 'routes-api.js', from: 'return off.filter(id=>!onMine.has(id));', to: 'return off;' },
  'routes: fake route id accepted':    { file: 'routes-api.js', from: 'if(!r) return {ok:false,status:404,error:"route not found"};', to: 'if(!r) return {ok:true,route:{}};' },
  'routes: dealer need not be a stop': { file: 'routes-api.js', from: 'if(!onRoute && !SC.seesAllDealers(me))', to: 'if(false)' },
  'geocode: fails open':               { file: 'geocode-api.js', from: 'if(need && safeEq(got,need))', to: 'if(!need || safeEq(got,need))' },
  'territory: fails open':             { file: 'territory-api.js', from: 'if(need && safeEq(got,need))', to: 'if(!need || safeEq(got,need))' },
  'ordering dealers-api: fails open':  { file: 'dealers-api.js', ordering: true, from: 'if(!need || got.length', to: 'if(need && got.length' },
  'ordering home-api: fails open':     { file: 'home-api.js', ordering: true, from: 'if(!need || got.length', to: 'if(need && got.length' },
  'staff: anyone bootstraps':          { file: 'staff-auth.js', from: 'const mayBootstrap = !staff && empty && !!boot && email===boot;', to: 'const mayBootstrap = !staff && empty;' },
  'staff: first sign-in sets password':{ file: 'staff-auth.js', from: 'const g=await tokenGrant(email,password);\n      if(!g.ok) return json(200,{ok:false,message:"Incorrect email or password.', to: 'let g=await tokenGrant(email,password);\n      if(!g.ok && staff){ await adminCreateUser(email,password); g=await tokenGrant(email,password); }\n      if(!g.ok) return json(200,{ok:false,message:"Incorrect email or password.' },
  'staff: no invite on add':           { file: 'staff-auth.js', from: 'try{ invite=await sendStaffLink(email,"invite"); }', to: 'try{ invite={ok:true}; }' },
  'staff: reset uses client redirect': { file: 'password-reset.js', from: 'body: JSON.stringify({ type: "recovery", email, options: { redirect_to } }),', to: 'body: JSON.stringify({ type: "recovery", email, options: { redirect_to: "https://evil.test/steal" } }),' },
  'email: dealer timeline open':       { file: 'email-sync-api.js', from: 'if(!(await SC.canAccessDealer(me,id,sbGet))) return json(403,{error:"Not your dealer"});', to: '' },
  'email: any message body':           { file: 'email-sync-api.js', from: 'if(!ownBox && !ownDealer) return json(403', to: 'if(false) return json(403' },
  'email: send onto any dealer':       { file: 'email-sync-api.js', from: 'if(dealerId && !(await SC.canAccessDealer(me,dealerId,sbGet))) return json(403', to: 'if(false) return json(403' },
  'tasks: any id':                     { file: 'crm-api.js', from: 'const own=await SC.authorizeRecord(me,"dealer_tasks",b.id,sbGet,{ownerFields:["assigned_rep","assigned_email"],optional:["assigned_email"]});', to: 'const own={ok:true};' },
  'scope: owner field ignored':        { file: '_scope.js', from: 'if((myEmail && v===myEmail) || (myRep && v===myRep)) return {ok:true,row};', to: '' },
  'scope: dealer mismatch ignored':    { file: '_scope.js', from: 'return {ok:false,status:403,error:"That record doesn\'t belong to this dealer."};', to: '{}' },
  'contacts: any id':                  { file: 'crm-api.js', from: 'const own=await SC.authorizeRecord(me,"dealer_contacts",id,sbGet,{dealerId:b.dealer_id});\n        if(!own.ok) return json(own.status,{error:own.error});\n        try{ await sbSend("PATCH",`dealer_contacts?id=eq.${encodeURIComponent(id)}&dealer_id=eq.${encodeURIComponent(b.dealer_id)}`', to: 'try{ await sbSend("PATCH",`dealer_contacts?id=eq.${encodeURIComponent(id)}`' },
  'pipeline: add anywhere':            { file: 'pipeline-api.js', from: 'if(b.dealer_id && !(await SC.canAccessDealer(me,b.dealer_id,sbGet))) return json(403', to: 'if(false) return json(403' },
  'pipeline: update any deal':         { file: 'pipeline-api.js', from: 'const own=await SC.authorizeRecord(me,"opportunities",b.id,sbGet,{ownerFields:["owner_rep","owner_email"],optional:["owner_email"]});', to: 'const own={ok:true};' },
  'pipeline: rep sets owner':          { file: 'pipeline-api.js', from: 'if(b.owner_rep!=null && manages)', to: 'if(b.owner_rep!=null)' },
  'pipeline: blank name matches':      { file: 'pipeline-api.js', from: '(!!myRep && String(o.owner_rep||"").toLowerCase()===myRep)', to: '(String(o.owner_rep||"").toLowerCase()===myRep)' },
  'schedule: any request id':          { file: 'schedule-api.js', from: 'if (req0 && !canWork(req0)) return json(403', to: 'if (false) return json(403' },
  'schedule: whole queue':             { file: 'schedule-api.js', from: '.catch(() => [])).filter(canWork);', to: '.catch(() => []));' },
  'schedule: book others':             { file: 'schedule-api.js', from: 'if (!manages && repEmail.toLowerCase() !== myEmail) return json(403', to: 'if (false) return json(403' },
  'sales import: anyone':              { file: 'sales-import-api.js', from: 'if(!["president","admin","owner"].includes(String(me.role||"").toLowerCase())) return json(403', to: 'if(false) return json(403' },
  'platform: anyone sets mode':        { file: 'platform-api.js', from: 'if(!MGMT) return json(403', to: 'if(false) return json(403' },
  'audiences: reps allowed':           { file: 'audiences-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'campaigns: reps allowed':           { file: 'campaign-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'cardchamp: reps allowed':           { file: 'partner-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'dealer mgr: portal access open':    { file: 'dealers-api.js', from: 'if(!seesAll && !(await ownsDealer(me,b.dealer_id))) return json(403,{error:"Not your dealer"});\r\n        const r=await computeDealerAccess', to: 'const r=await computeDealerAccess' },
  'orders: out-of-book orders shown':  { file: 'orders-admin.js', from: 'list=list.filter(o=>!!(o.dealer_id && sc.ids && sc.ids.has(String(o.dealer_id))));', to: '' },
  'health: out-of-book rows shown':    { file: 'health-api.js', from: 'rows=rows.filter(r=>!!(sc.ids && sc.ids.has(String(r.dealer_id))));', to: '' },
  'analytics: contact details leak':   { file: 'analytics.js', from: 'for (const nm of Object.keys(dealerInfo)) if (!mine.has(nm)) delete dealerInfo[nm];', to: '' },
  // ---- Phase 0D: one owner (dealers.rep_email), one resolver, one writer ----
  '0D scope: name beats email':        { file: '_scope.js', from: 'if(o.storedEmail) return !!myEmail && o.storedEmail===myEmail;', to: 'if(o.storedEmail && !o.storedRep) return !!myEmail && o.storedEmail===myEmail;' },
  '0D scope: directory beats row':     { file: '_scope.js', from: 'if(o.storedRep)   return !!myRep && low(o.storedRep)===myRep;', to: 'if(o.storedRep && !o.dirReps) return !!myRep && low(o.storedRep)===myRep;' },
  '0D scope: family ignores owner':    { file: '_scope.js', from: 'const mineOrOpen=o=>!o.explicit || ownsDirectly(o, myEmail, myRep);', to: 'const mineOrOpen=o=>true;' },
  '0D scope: first page only':         { file: '_scope.js', from: 'for(let off=0; off<500000; off+=PAGE){', to: 'for(let off=0; off<1; off+=PAGE){' },
  '0D labels: name beats email':       { file: '_scope.js', from: 'if(storedEmail){ email=storedEmail; rep=repByEmail[storedEmail]||storedRep; source="email"; }', to: 'if(storedEmail){ email=storedEmail; rep=storedRep||repByEmail[storedEmail]; source="email"; }' },
  '0D owner: email not written':       { file: '_scope.js', from: '{rep_name:rep,rep_email:email},{Prefer:"return=minimal"}); }', to: '{rep_name:rep},{Prefer:"return=minimal"}); }' },
  '0D owner: directory not synced':    { file: '_scope.js', from: 'if(dirRows.length) await sbSend(', to: 'if(false) await sbSend(' },
  '0D owner: work stays behind':       { file: '_scope.js', from: 'moved.tasks+=await move("dealer_tasks","assigned_rep",chunk,p,{assigned_rep:rep});', to: '' },
  '0D owner: deals stay behind':       { file: '_scope.js', from: 'moved.opportunities+=await move("opportunities","owner_rep",chunk,p,{owner_rep:rep});', to: '' },
  '0D owner: third-party work moved':  { file: '_scope.js', from: 'const who=prev?`${col}=eq.${encodeURIComponent(prev)}`:`${col}=is.null`;', to: 'const who="id=not.is.null";' },
  '0D owner: closed work moved':       { file: '_scope.js', from: '&status=eq.open&${who}&select=id`', to: '&${who}&select=id`' },
  '0D dealer360: name-only = directory':{ file: 'dealers-api.js', from: 'const id=b.dealer_id || (b.dealer_name ? await SC.dealerIdByName(b.dealer_name, sbGet) : null);', to: 'const id=b.dealer_id;' },
  '0D bulk: old writer':               { file: 'dealers-api.js', from: 'const r=await SC.setDealerOwner(ids, rep, {sbGet,sbSend});\r\n        return json(200,{ok:true,updated:ids.length', to: 'for(const id of ids) await sbSend("PATCH",`dealers?id=eq.${id}`,{rep_name:rep},{Prefer:"return=minimal"}); const r={};\r\n        return json(200,{ok:true,updated:ids.length' },
  '0D assign.js: directory only':      { file: 'assign.js', from: 'const owner = dealerId ? await SC.setDealerOwner(', to: 'const owner = false ? await SC.setDealerOwner(' },
  '0D ordering: directory only':       { file: 'dealers-api.js', ordering: true, from: 'const owner=await setOwnerByName(b.dealer_name, rep).catch(()=>null);', to: 'const owner=null;' },
  '0D ordering: rewrites unchanged':   { file: 'dealers-api.js', ordering: true, from: 'if(low(prev)===low(rep) && low(d.rep_email)===low(email)) return {dealer_id:d.id,changed:false};', to: '' },
  '0D dealer mgr: name filter':        { file: 'dealers-api.js', from: 'state.dealers=(state.dealers||[]).filter(d=> sc.ids && sc.ids.has(String(d.id)));', to: 'state.dealers=(state.dealers||[]).filter(d=> String(d.rep||"").trim().toLowerCase()===String(me.rep_name||"").trim().toLowerCase());' },
  '0D map: everything':                { file: 'geocode-api.js', from: 'const mine=p=> !!(sc.ids && p.dealer_id && sc.ids.has(String(p.dealer_id)));', to: 'const mine=p=>true;' },
  '0D health: cache label':            { file: 'health-api.js', from: 'if(OI) rows=rows.map(r=>({...r, rep_name:OI.repOf(r.dealer_id)||null}));', to: '' },
  '0D analytics: no owner index':      { file: 'analytics.js', from: 'let OI = null; try { OI = await SC.ownerIndex(sbGet); } catch (e) { OI = null; }', to: 'let OI = null;' },
  '0D analytics: HQ via master':       { file: 'analytics.js', from: 'for (const nm of [...mine]) if (dealerNames.has(nm) && !inBook.has(nm)) mine.delete(nm);', to: 'for (const f of facts) mine.add(f.master);' },
  '0D pipeline: whole network':        { file: 'pipeline-api.js', from: 'const outOfBook=id=>isRep && !(sc && sc.ids && sc.ids.has(String(id)));', to: 'const outOfBook=id=>false;' },
  '0D c360: whole network':            { file: 'command360-api.js', from: 'idSet=new Set([...(sc.ids||[])]);', to: 'idSet=null;' },
  '0D marketing: whole network':       { file: 'marketing-api.js', from: 'const repSet = all ? null :', to: 'const repSet = true ? null :' },
  '0D engine: directory label':        { file: '_engine.js', from: '      lines:o.lines.size,rep_name:repOfId(id)||null,', to: '      lines:o.lines.size,rep_name:null,' },
  '0D report: directory label':        { file: '_report.js', from: "  const repByName=dir||{};", to: "  const repByName={};" },
  // ---- Phase 0F: a visit runs once ----
  '0F claim always wins':              { file: 'routes-api.js', from: 'firstCompletion=Array.isArray(won)&&won.length>0;', to: 'firstCompletion=true;' },
  '0F claim not conditional':          { file: 'routes-api.js', from: '&dealer_id=eq.${encodeURIComponent(did)}&completed_at=is.null`', to: '&dealer_id=eq.${encodeURIComponent(did)}`' },
  '0F save status regresses':          { file: 'routes-api.js', from: 'const newStatus=(prev&&prev.completed_at) ? "completed" : visitStatusMax(prev&&prev.status, status);', to: 'const newStatus=status;' },
  '0F check-in status regresses':      { file: 'routes-api.js', from: 'const status=prev ? visitStatusMax(prev.status,"checked_in") : "checked_in";', to: 'const status="checked_in";' },
  '0F check-in resets arrival':        { file: 'routes-api.js', from: 'if(prev && prev.checkin_at) return json(200,{ok:true,checkin_at:prev.checkin_at,status:prev.status||"checked_in",already:true});', to: '' },
  '0F any status accepted':            { file: 'routes-api.js', from: 'if(!VISIT_STATUSES.includes(status)) return json(400', to: 'if(false) return json(400' },
  '0F no heal':                        { file: 'routes-api.js', from: 'if(rowPath && !firstCompletion) await sbSend(', to: 'if(false) await sbSend(' },
  '0F off-route: new report each time':{ file: 'routes-api.js', from: '`dealer_visit_reports?route_id=is.null&dealer_id=eq.${encodeURIComponent(did)}&rep_email=eq.${encodeURIComponent((meNow&&meNow.email)||"")}&completed_at=is.null&${sel}&order=updated_at.desc&limit=1`', to: '`dealer_visit_reports?id=eq.none&${sel}`' },
  '0F off-route: replay is a new visit':{ file: 'routes-api.js', from: 'if(same) prev=same;', to: '' },
  // ---- Phase 0G: field outbox (scheduled-routes.html; applied by phase0-outbox.test.js) ----
  '0G one queue for everyone':         { file: 'scheduled-routes.html', from: 'function obKey(kind){ const u=obUser(); return u ? `sr_${kind}_${u}` : `sr_${kind}__noone`; }', to: 'function obKey(kind){ return `sr_${kind}`; }' },
  '0G old queue sent automatically':   { file: 'scheduled-routes.html', from: '  if(moved) setQuarantine(q);', to: '  if(moved){ const a=outbox(); for(const x of q) a.push(x); setOutbox(a); }' },
  '0G refusals retried forever':       { file: 'scheduled-routes.html', from: 'if(r.status>=400) return {kind:"rejected",status:r.status,j};', to: 'if(r.status>=400) return {kind:"retry",status:r.status,j};' },
  '0G "ok:false" counted as sent':     { file: 'scheduled-routes.html', from: '  return {kind:"rejected",status:r.status,j};\n}', to: '  return {kind:"ok",status:r.status,j};\n}' },
  '0G failure skipped, order lost':    { file: 'scheduled-routes.html', from: 'if(k>=0){ cur[k].tries=(cur[k].tries||0)+1; cur[k].last_error=res.status?("HTTP "+res.status):"no connection"; setOutbox(cur); }\n      break;', to: 'setOutbox(outbox().filter(x=>x.id!==item.id).concat([item])); continue;' },
  '0G lapsed session ignored':         { file: 'scheduled-routes.html', from: 'if(res.kind==="auth"){ obSignedOut(); break; }', to: '' },
  '0G refusal queued on save':         { file: 'scheduled-routes.html', from: '  if(res.kind==="rejected") return {sent:false,rejected:true,error:obErrorText(res)};\n  enqueue(body);', to: '  enqueue(body);' },
  '0G new save jumps the queue':       { file: 'scheduled-routes.html', from: '  if(outbox().length){                                     // earlier items first', to: '  if(false){                                     // earlier items first' },
  '0G resend loop on full storage':    { file: 'scheduled-routes.html', from: 'if(seen.has(item.id)) break; seen.add(item.id);', to: '' },
  '0F visit tasks dropped (mixed keys)':{ file: 'routes-api.js', from: 'tasks.map(x=>Object.assign({due_date:null},x))', to: 'tasks' },
  // ---- Phase 0H: contact safety ----
  '0H blanks erase on upsert':         { file: '_upsert.js', from: 'if((keep || []).includes(k) || !isBlank(v)) out[k] = v;', to: 'out[k] = v;' },
  '0H mixed shapes in one insert':     { file: '_upsert.js', from: 'for(const group of groupByShape((rows || []).map(r => stripBlank(r, opts.keep)))){', to: 'for(const group of [(rows || []).map(r => stripBlank(r, opts.keep))]){' },
  '0H replace without confirmation':   { file: 'dealers-api.js', from: 'if(replace && !preview && b.confirm_replace!==true)', to: 'if(false)' },
  '0H preview writes':                 { file: 'dealers-api.js', from: '        if(preview){\r\n', to: '        if(false){\r\n' },
  '0H replace wipes everyone':         { file: 'dealers-api.js', from: 'try{ await sbSend("DELETE",`dealer_contacts?dealer_id=in.(${inq})`', to: 'try{ await sbSend("DELETE",`dealer_contacts?dealer_id=not.is.null`' },
  '0H quick-add erases':               { file: 'crm-api.js', from: 'UP.stripBlank({dealer_id:b.dealer_id,email,...fields},["dealer_id","email"])', to: '{dealer_id:b.dealer_id,email,...fields}' },
  // ---- Phase 0I / 0J: tasks + opportunities ----
  '0I priority order inverted':        { file: 'crm-api.js', from: 'const PRANK={high:0,normal:1,medium:1,low:2};', to: 'const PRANK={high:2,normal:1,medium:1,low:0};' },
  '0I rep list ignores email':         { file: 'crm-api.js', from: '(em && String(t.assigned_email||"").toLowerCase()===em) || ', to: '' },
  '0I first page only':                { file: 'crm-api.js', from: 'if(seesAll) tasks=await sbGetAll(`dealer_tasks?status=eq.${status}&select=*`,"id")', to: 'if(seesAll) tasks=await sbGet(`dealer_tasks?status=eq.${status}&select=*&limit=1000`)' },
  '0I completed_by not recorded':      { file: 'crm-api.js', from: ',completed_by:status==="open"?null:(me.email||me.name||null)};', to: '};' },
  '0I no fallback before migration':   { file: '_upsert.js', from: "if(!/PGRST204|Could not find the '[^']*' column/i.test(String(e && e.message || e))) throw e;", to: 'throw e;' },
  '0I engine closes as nobody':        { file: '_engine.js', from: '{status:"dismissed",done_at:new Date().toISOString(),completed_by:"system"}', to: '{status:"dismissed",done_at:new Date().toISOString()}' },
  '0I dismissals counted as done':     { file: 'rep-usage-api.js', from: 't.status==="done" && t.done_at && t.done_at>=D.since &&', to: 't.done_at &&' },
  '0I credit goes to the assignee':    { file: 'rep-usage-api.js', from: '(t.completed_by ? isMine(k, t.completed_by) : isMine(k, t.assigned_email, t.assigned_rep))).length;', to: 'isMine(k, t.assigned_email, t.assigned_rep)).length;' },
  '0I record check needs new columns': { file: '_scope.js', from: 'const opt=new Set(opts.optional||[]); const base=cols.filter(c=>!opt.has(c));', to: 'const base=cols;' },
  '0J board ignores email owner':      { file: 'pipeline-api.js', from: '(!!myEmail && String(o.owner_email||"").toLowerCase()===myEmail) || ', to: '' },
  '0J new deal without email':         { file: 'pipeline-api.js', from: 'if(!manages || !clean(b.owner_rep,120)) row.owner_email=String(me.email||"").toLowerCase()||null;', to: '' },
  '0J update ignores email owner':     { file: 'pipeline-api.js', from: '{ownerFields:["owner_rep","owner_email"],optional:["owner_email"]}', to: '{ownerFields:["owner_rep"]}' },
  '0I badge counts by name only':      { file: 'crm-api.js', from: 'const n=(await repTasks(me,"open","id,assigned_rep,assigned_email")).length;', to: 'const n=((await sbGet(`dealer_tasks?status=eq.open&select=assigned_rep`).catch(()=>[]))||[]).filter(t=>String(t.assigned_rep||"").toLowerCase()===String(me.rep_name||"").toLowerCase()).length;' },
  // ---- Phase 0K: Relations = every dealer, no management powers ----
  '0K c360: Relations own book only':  { file: 'command360-api.js', from: 'if(ADMIN || RELATIONS){', to: 'if(ADMIN){' },
  '0K c360: Relations sees email review':{ file: 'command360-api.js', from: 'if(RELATIONS) emUn=[];', to: '' },
  '0K marketing: Relations own book':  { file: 'marketing-api.js', from: 'const all=SC.seesAllDealers(me);', to: 'const all=me.role==="president";' },
  '0K insights: team results to Relations':{ file: 'call-brief-api.js', from: 'by_rep: isAdmin(me) ?', to: 'by_rep: seesAllDealers(me) ?' },
  // ---- Phase 0L: one landing rule, off by default ----
  '0L management sent to rep home':    { file: 'staff-auth.js', from: 'if(["president","admin","owner"].includes(role)) return "/admin/";', to: '' },
  '0L off-site landing accepted':      { file: 'staff-auth.js', from: '&& /^\\/admin\\/[A-Za-z0-9._\\/-]*$/.test(cfg.url) && !cfg.url.includes(".."))', to: ')' },
  '0L pilot ignores the list':         { file: 'staff-auth.js', from: 'mode==="pilot" && Array.isArray(cfg.emails) && cfg.emails.map(e=>String(e||"").trim().toLowerCase()).includes(String(s.email||"").toLowerCase())', to: 'mode==="pilot"' },
  '0L "off" behaves as "on"':          { file: 'staff-auth.js', from: 'if(url && mode==="on") return url;', to: 'if(url) return url;' },
  '0L Relations moved too':            { file: 'staff-auth.js', from: '|| role!=="rep") return REP_HOME;', to: ') return REP_HOME;' },
  // ---- Oct 2 decisions: Relations reads the Dealer Manager; the Admin dashboard is management's ----
  '0K Relations may write Dealer Manager':{ file: 'dealers-api.js', from: 'if(role==="relations" && !RELATIONS_READS.has(act)) return json(403,', to: 'if(false) return json(403,' },
  '0K Relations blocked from reads':   { file: 'dealers-api.js', from: 'const RELATIONS_READS=new Set(["portal_access","preview_link"]);', to: 'const RELATIONS_READS=new Set([]);' },
  '0K Relations edit controls shown':  { file: 'dealers.html', from: 'const ro=isRelations();', to: 'const ro=false;' },
  '0K Relations verify link shown':    { file: 'dealers.html', from: 'pending verification</span>${isRelations()?"":', to: 'pending verification</span>${false?"":' },
  '0K D360 company edit to Relations': { file: 'dealer.html', from: '.toLowerCase()==="relations"?"":`<button class="btn ghost sm" onclick="editCompany()">', to: '.toLowerCase()==="nobody"?"":`<button class="btn ghost sm" onclick="editCompany()">' },
  '0L Relations stays on Admin dash':  { file: 'index.html', from: 'if(role!=="rep"&&role!=="relations") return null;', to: 'if(role!=="rep") return null;' },
  '0L management sent off Admin dash': { file: 'index.html', from: 'if(role!=="rep"&&role!=="relations") return null;', to: 'if(!role) return null;' },
  '0F replay compared by key order':   { file: 'routes-api.js', from: 'canonJson(l.fields||{})===want', to: 'JSON.stringify(l.fields||{})===JSON.stringify(fields)' },
  '0F replay checks only the last visit':{ file: 'routes-api.js', from: 'const same=(done||[]).find(l=>l && l.completed_at && canonJson(l.fields||{})===want); if(same) prev=same;', to: 'const l=(done||[])[0]; if(l && l.completed_at && canonJson(l.fields||{})===want) prev=l;' },
  '0F replay window removed':          { file: 'routes-api.js', from: '&completed_at=gte.${encodeURIComponent(since)}', to: '' },
};
