/* Phase 0 mutants: each undoes ONE protection, in memory only. phase0.mutants.js runs both
   Phase 0 suites against each and requires at least one test to fail — a mutant that survives
   means that protection is untested. */
module.exports = {
  'settings: no allowlist':            { file: 'routes-api.js', from: 'if(!rule) return json(403,{error:"That setting isn\'t available here."});', to: 'if(!rule) return json(200,{ok:true,value:((await sbGet(`app_settings?key=eq.${encodeURIComponent(key)}&select=value`).catch(()=>[]))[0]||{}).value||null});' },
  'settings: whole row returned':      { file: 'routes-api.js', from: 'value:v?pickFields(v,rule.fields):null', to: 'value:v' },
  'settings: any key writable':        { file: 'routes-api.js', from: 'if(!rule||!rule.writable) return json(403', to: 'if(false) return json(403' },
  'routes: dealer guard off':          { file: 'routes-api.js', from: 'if(off.length) return json(403,{error:"Not your dealer",dealer_ids:off});', to: '' },
  'routes: route grant grants all':    { file: 'routes-api.js', from: 'return off.filter(id=>!onMine.has(id));', to: 'return [];' },
  'routes: no route grant':            { file: 'routes-api.js', from: 'return off.filter(id=>!onMine.has(id));', to: 'return off;' },
  'routes: fake route id accepted':    { file: 'routes-api.js', from: 'if(!r) return {ok:false,status:404,error:"route not found"};', to: 'if(!r) return {ok:true,route:{}};' },
  'routes: dealer need not be a stop': { file: 'routes-api.js', from: 'if(!onRoute && !SC.seesAllDealers(me))', to: 'if(false)' },
  'geocode: fails open':               { file: 'geocode-api.js', from: 'if(need && safeEq(got,need))', to: 'if(!need || safeEq(got,need))' },
  'territory: fails open':             { file: 'territory-api.js', from: 'if(need && safeEq(got,need))', to: 'if(!need || safeEq(got,need))' },
  'ordering dealers-api: fails open':  { file: 'dealers-api.js', ordering: true, from: 'if(!need || got.length', to: 'if(need && got.length' },
  'ordering home-api: fails open':     { file: 'home-api.js', ordering: true, from: 'if(!need || got.length', to: 'if(need && got.length' },
  'staff: anyone bootstraps':          { file: 'staff-auth.js', from: 'const mayBootstrap = !staff && empty && !!boot && email===boot;', to: 'const mayBootstrap = !staff && empty;' },
  'staff: first sign-in sets password':{ file: 'staff-auth.js', from: 'const g=await tokenGrant(email,password);\n      if(!g.ok) return json(200,{ok:false,message:"Incorrect email or password.', to: 'let g=await tokenGrant(email,password);\n      if(!g.ok && staff){ await adminCreateUser(email,password); g=await tokenGrant(email,password); }\n      if(!g.ok) return json(200,{ok:false,message:"Incorrect email or password.' },
  'staff: no invite on add':           { file: 'staff-auth.js', from: 'try{ invite=await sendStaffLink(email,"invite"); }', to: 'try{ invite={ok:true}; }' },
  'staff: reset uses client redirect': { file: 'password-reset.js', from: 'body: JSON.stringify({ type: "recovery", email, options: { redirect_to } }),', to: 'body: JSON.stringify({ type: "recovery", email, options: { redirect_to: "https://evil.test/steal" } }),' },
  'email: dealer timeline open':       { file: 'email-sync-api.js', from: 'if(!(await SC.canAccessDealer(me,id,sbGet))) return json(403,{error:"Not your dealer"});', to: '' },
  'email: any message body':           { file: 'email-sync-api.js', from: 'if(!ownBox && !ownDealer) return json(403', to: 'if(false) return json(403' },
  'email: send onto any dealer':       { file: 'email-sync-api.js', from: 'if(dealerId && !(await SC.canAccessDealer(me,dealerId,sbGet))) return json(403', to: 'if(false) return json(403' },
  'tasks: any id':                     { file: 'crm-api.js', from: 'const own=await SC.authorizeRecord(me,"dealer_tasks",b.id,sbGet,{ownerFields:["assigned_rep","assigned_email"],optional:["assigned_email"]});', to: 'const own={ok:true};' },
  'scope: owner field ignored':        { file: '_scope.js', from: 'if((myEmail && v===myEmail) || (myRep && v===myRep)) return {ok:true,row};', to: '' },
  'scope: dealer mismatch ignored':    { file: '_scope.js', from: 'return {ok:false,status:403,error:"That record doesn\'t belong to this dealer."};', to: '{}' },
  'contacts: any id':                  { file: 'crm-api.js', from: 'const own=await SC.authorizeRecord(me,"dealer_contacts",id,sbGet,{dealerId:b.dealer_id});\n        if(!own.ok) return json(own.status,{error:own.error});\n        try{ await sbSend("PATCH",`dealer_contacts?id=eq.${encodeURIComponent(id)}&dealer_id=eq.${encodeURIComponent(b.dealer_id)}`', to: 'try{ await sbSend("PATCH",`dealer_contacts?id=eq.${encodeURIComponent(id)}`' },
  'pipeline: add anywhere':            { file: 'pipeline-api.js', from: 'if(b.dealer_id && !(await SC.canAccessDealer(me,b.dealer_id,sbGet))) return json(403', to: 'if(false) return json(403' },
  'pipeline: update any deal':         { file: 'pipeline-api.js', from: 'const own=await SC.authorizeRecord(me,"opportunities",b.id,sbGet,{ownerFields:["owner_rep","owner_email"],optional:["owner_email"]});', to: 'const own={ok:true};' },
  'pipeline: rep sets owner':          { file: 'pipeline-api.js', from: 'if(b.owner_rep!=null && manages)', to: 'if(b.owner_rep!=null)' },
  'pipeline: blank name matches':      { file: 'pipeline-api.js', from: '(!!myRep && String(o.owner_rep||"").toLowerCase()===myRep)', to: '(String(o.owner_rep||"").toLowerCase()===myRep)' },
  'schedule: any request id':          { file: 'schedule-api.js', from: 'if (req0 && !canWork(req0)) return json(403', to: 'if (false) return json(403' },
  'schedule: whole queue':             { file: 'schedule-api.js', from: '.catch(() => [])).filter(canWork);', to: '.catch(() => []));' },
  'schedule: book others':             { file: 'schedule-api.js', from: 'if (!manages && repEmail.toLowerCase() !== myEmail) return json(403', to: 'if (false) return json(403' },
  'sales import: anyone':              { file: 'sales-import-api.js', from: 'if(!["president","admin","owner"].includes(String(me.role||"").toLowerCase())) return json(403', to: 'if(false) return json(403' },
  'platform: anyone sets mode':        { file: 'platform-api.js', from: 'if(!MGMT) return json(403', to: 'if(false) return json(403' },
  'audiences: reps allowed':           { file: 'audiences-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'campaigns: reps allowed':           { file: 'campaign-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'cardchamp: reps allowed':           { file: 'partner-api.js', from: 'if(String(me.role||"rep").toLowerCase()==="rep") return json(403', to: 'if(false) return json(403' },
  'dealer mgr: portal access open':    { file: 'dealers-api.js', from: 'if(!seesAll && !(await ownsDealer(me,b.dealer_id))) return json(403,{error:"Not your dealer"});\r\n        const r=await computeDealerAccess', to: 'const r=await computeDealerAccess' },
  'orders: out-of-book orders shown':  { file: 'orders-admin.js', from: 'list=list.filter(o=>!!(o.dealer_id && sc.ids && sc.ids.has(String(o.dealer_id))));', to: '' },
  'health: out-of-book rows shown':    { file: 'health-api.js', from: 'rows=rows.filter(r=>!!(sc.ids && sc.ids.has(String(r.dealer_id))));', to: '' },
  'analytics: contact details leak':   { file: 'analytics.js', from: 'for (const nm of Object.keys(dealerInfo)) if (!mine.has(nm)) delete dealerInfo[nm];', to: '' },
  // ---- Phase 0D: one owner (dealers.rep_email), one resolver, one writer ----
  '0D scope: name beats email':        { file: '_scope.js', from: 'if(o.storedEmail) return !!myEmail && o.storedEmail===myEmail;', to: 'if(o.storedEmail && !o.storedRep) return !!myEmail && o.storedEmail===myEmail;' },
  '0D scope: directory beats row':     { file: '_scope.js', from: 'if(o.storedRep)   return !!myRep && low(o.storedRep)===myRep;', to: 'if(o.storedRep && !o.dirReps) return !!myRep && low(o.storedRep)===myRep;' },
  '0D scope: family ignores owner':    { file: '_scope.js', from: 'const mineOrOpen=o=>!o.explicit || ownsDirectly(o, myEmail, myRep);', to: 'const mineOrOpen=o=>true;' },
  '0D scope: first page only':         { file: '_scope.js', from: 'for(let off=0; off<500000; off+=PAGE){', to: 'for(let off=0; off<1; off+=PAGE){' },
  '0D labels: name beats email':       { file: '_scope.js', from: 'if(storedEmail){ email=storedEmail; rep=repByEmail[storedEmail]||storedRep; source="email"; }', to: 'if(storedEmail){ email=storedEmail; rep=storedRep||repByEmail[storedEmail]; source="email"; }' },
  '0D owner: email not written':       { file: '_scope.js', from: '{rep_name:rep,rep_email:email},{Prefer:"return=minimal"}); }', to: '{rep_name:rep},{Prefer:"return=minimal"}); }' },
  '0D owner: directory not synced':    { file: '_scope.js', from: 'if(dirRows.length) await sbSend(', to: 'if(false) await sbSend(' },
  '0D owner: work stays behind':       { file: '_scope.js', from: 'moved.tasks+=await move("dealer_tasks","assigned_rep",chunk,p,{assigned_rep:rep});', to: '' },
  '0D owner: deals stay behind':       { file: '_scope.js', from: 'moved.opportunities+=await move("opportunities","owner_rep",chunk,p,{owner_rep:rep});', to: '' },
  '0D owner: third-party work moved':  { file: '_scope.js', from: 'const who=prev?`${col}=eq.${encodeURIComponent(prev)}`:`${col}=is.null`;', to: 'const who="id=not.is.null";' },
  '0D owner: closed work moved':       { file: '_scope.js', from: '&status=eq.open&${who}&select=id`', to: '&${who}&select=id`' },
  '0D dealer360: name-only = directory':{ file: 'dealers-api.js', from: 'const id=b.dealer_id || (b.dealer_name ? await SC.dealerIdByName(b.dealer_name, sbGet) : null);', to: 'const id=b.dealer_id;' },
  '0D bulk: old writer':               { file: 'dealers-api.js', from: 'const r=await SC.setDealerOwner(ids, rep, {sbGet,sbSend});\r\n        return json(200,{ok:true,updated:ids.length', to: 'for(const id of ids) await sbSend("PATCH",`dealers?id=eq.${id}`,{rep_name:rep},{Prefer:"return=minimal"}); const r={};\r\n        return json(200,{ok:true,updated:ids.length' },
  '0D assign.js: directory only':      { file: 'assign.js', from: 'const owner = dealerId ? await SC.setDealerOwner(', to: 'const owner = false ? await SC.setDealerOwner(' },
  '0D ordering: directory only':       { file: 'dealers-api.js', ordering: true, from: 'const owner=await setOwnerByName(b.dealer_name, rep).catch(()=>null);', to: 'const owner=null;' },
  '0D ordering: rewrites unchanged':   { file: 'dealers-api.js', ordering: true, from: 'if(low(prev)===low(rep) && low(d.rep_email)===low(email)) return {dealer_id:d.id,changed:false};', to: '' },
  '0D dealer mgr: name filter':        { file: 'dealers-api.js', from: 'state.dealers=(state.dealers||[]).filter(d=> sc.ids && sc.ids.has(String(d.id)));', to: 'state.dealers=(state.dealers||[]).filter(d=> String(d.rep||"").trim().toLowerCase()===String(me.rep_name||"").trim().toLowerCase());' },
  '0D map: everything':                { file: 'geocode-api.js', from: 'const mine=p=> !!(sc.ids && p.dealer_id && sc.ids.has(String(p.dealer_id)));', to: 'const mine=p=>true;' },
  '0D health: cache label':            { file: 'health-api.js', from: 'if(OI) rows=rows.map(r=>({...r, rep_name:OI.repOf(r.dealer_id)||null}));', to: '' },
  '0D analytics: no owner index':      { file: 'analytics.js', from: 'let OI = null; try { OI = await SC.ownerIndex(sbGet); } catch (e) { OI = null; }', to: 'let OI = null;' },
  '0D analytics: HQ via master':       { file: 'analytics.js', from: 'for (const nm of [...mine]) if (dealerNames.has(nm) && !inBook.has(nm)) mine.delete(nm);', to: 'for (const f of facts) mine.add(f.master);' },
  '0D pipeline: whole network':        { file: 'pipeline-api.js', from: 'const outOfBook=id=>isRep && !(sc && sc.ids && sc.ids.has(String(id)));', to: 'const outOfBook=id=>false;' },
  '0D c360: whole network':            { file: 'command360-api.js', from: 'idSet=new Set([...(sc.ids||[])]);', to: 'idSet=null;' },
  '0D marketing: whole network':       { file: 'marketing-api.js', from: 'const repSet = all ? null :', to: 'const repSet = true ? null :' },
  '0D engine: directory label':        { file: '_engine.js', from: '      lines:o.lines.size,rep_name:repOfId(id)||null,', to: '      lines:o.lines.size,rep_name:null,' },
  '0D report: directory label':        { file: '_report.js', from: "  const repByName=dir||{};", to: "  const repByName={};" },
  // ---- Phase 0F: a visit runs once ----
  '0F claim always wins':              { file: 'routes-api.js', from: 'firstCompletion=Array.isArray(won)&&won.length>0;', to: 'firstCompletion=true;' },
  '0F claim not conditional':          { file: 'routes-api.js', from: '&dealer_id=eq.${encodeURIComponent(did)}&completed_at=is.null`', to: '&dealer_id=eq.${encodeURIComponent(did)}`' },
  '0F save status regresses':          { file: 'routes-api.js', from: 'const newStatus=(prev&&prev.completed_at) ? "completed" : visitStatusMax(prev&&prev.status, status);', to: 'const newStatus=status;' },
  '0F check-in status regresses':      { file: 'routes-api.js', from: 'const status=prev ? visitStatusMax(prev.status,"checked_in") : "checked_in";', to: 'const status="checked_in";' },
  '0F check-in resets arrival':        { file: 'routes-api.js', from: 'if(prev && prev.checkin_at) return json(200,{ok:true,checkin_at:prev.checkin_at,status:prev.status||"checked_in",already:true});', to: '' },
  '0F any status accepted':            { file: 'routes-api.js', from: 'if(!VISIT_STATUSES.includes(status)) return json(400', to: 'if(false) return json(400' },
  '0F no heal':                        { file: 'routes-api.js', from: 'if(rowPath && !firstCompletion) await sbSend(', to: 'if(false) await sbSend(' },
  '0F off-route: new report each time':{ file: 'routes-api.js', from: '`dealer_visit_reports?route_id=is.null&dealer_id=eq.${encodeURIComponent(did)}&rep_email=eq.${encodeURIComponent((meNow&&meNow.email)||"")}&completed_at=is.null&${sel}&order=updated_at.desc&limit=1`', to: '`dealer_visit_reports?id=eq.none&${sel}`' },
  '0F off-route: replay is a new visit':{ file: 'routes-api.js', from: 'if(same) prev=same;', to: '' },
  // ---- Phase 0G: field outbox (scheduled-routes.html; applied by phase0-outbox.test.js) ----
  '0G one queue for everyone':         { file: 'scheduled-routes.html', from: 'function obKey(kind){ const u=obUser(); return u ? `sr_${kind}_${u}` : `sr_${kind}__noone`; }', to: 'function obKey(kind){ return `sr_${kind}`; }' },
  '0G old queue sent automatically':   { file: 'scheduled-routes.html', from: '  if(moved) setQuarantine(q);', to: '  if(moved){ const a=outbox(); for(const x of q) a.push(x); setOutbox(a); }' },
  '0G refusals retried forever':       { file: 'scheduled-routes.html', from: 'if(r.status>=400) return {kind:"rejected",status:r.status,j};', to: 'if(r.status>=400) return {kind:"retry",status:r.status,j};' },
  '0G "ok:false" counted as sent':     { file: 'scheduled-routes.html', from: '  return {kind:"rejected",status:r.status,j};\n}', to: '  return {kind:"ok",status:r.status,j};\n}' },
  '0G failure skipped, order lost':    { file: 'scheduled-routes.html', from: 'if(k>=0){ cur[k].tries=(cur[k].tries||0)+1; cur[k].last_error=res.status?("HTTP "+res.status):"no connection"; setOutbox(cur); }\n      break;', to: 'setOutbox(outbox().filter(x=>x.id!==item.id).concat([item])); continue;' },
  '0G lapsed session ignored':         { file: 'scheduled-routes.html', from: 'if(res.kind==="auth"){ obSignedOut(); break; }', to: '' },
  '0G refusal queued on save':         { file: 'scheduled-routes.html', from: '  if(res.kind==="rejected") return {sent:false,rejected:true,error:obErrorText(res)};\n  enqueue(body);', to: '  enqueue(body);' },
  '0G new save jumps the queue':       { file: 'scheduled-routes.html', from: '  if(outbox().length){                                     // earlier items first', to: '  if(false){                                     // earlier items first' },
  '0G resend loop on full storage':    { file: 'scheduled-routes.html', from: 'if(seen.has(item.id)) break; seen.add(item.id);', to: '' },
  '0F visit tasks dropped (mixed keys)':{ file: 'routes-api.js', from: 'tasks.map(x=>Object.assign({due_date:null},x))', to: 'tasks' },
  // ---- Phase 0H: contact safety ----
  '0H blanks erase on upsert':         { file: '_upsert.js', from: 'if((keep || []).includes(k) || !isBlank(v)) out[k] = v;', to: 'out[k] = v;' },
  '0H mixed shapes in one insert':     { file: '_upsert.js', from: 'for(const group of groupByShape((rows || []).map(r => stripBlank(r, opts.keep)))){', to: 'for(const group of [(rows || []).map(r => stripBlank(r, opts.keep))]){' },
  '0H replace without confirmation':   { file: 'dealers-api.js', from: 'if(replace && !preview && b.confirm_replace!==true)', to: 'if(false)' },
  '0H preview writes':                 { file: 'dealers-api.js', from: '        if(preview){\r\n', to: '        if(false){\r\n' },
  '0H replace wipes everyone':         { file: 'dealers-api.js', from: 'try{ await sbSend("DELETE",`dealer_contacts?dealer_id=in.(${inq})`', to: 'try{ await sbSend("DELETE",`dealer_contacts?dealer_id=not.is.null`' },
  '0H quick-add erases':               { file: 'crm-api.js', from: 'UP.stripBlank({dealer_id:b.dealer_id,email,...fields},["dealer_id","email"])', to: '{dealer_id:b.dealer_id,email,...fields}' },
  // ---- Phase 0I / 0J: tasks + opportunities ----
  '0I priority order inverted':        { file: 'crm-api.js', from: 'const PRANK={high:0,normal:1,medium:1,low:2};', to: 'const PRANK={high:2,normal:1,medium:1,low:0};' },
  '0I rep list ignores email':         { file: 'crm-api.js', from: '(em && String(t.assigned_email||"").toLowerCase()===em) || ', to: '' },
  '0I first page only':                { file: 'crm-api.js', from: 'if(seesAll) tasks=await sbGetAll(`dealer_tasks?status=eq.${status}&select=*`,"id")', to: 'if(seesAll) tasks=await sbGet(`dealer_tasks?status=eq.${status}&select=*&limit=1000`)' },
  '0I completed_by not recorded':      { file: 'crm-api.js', from: ',completed_by:status==="open"?null:(me.email||me.name||null),updated_at:', to: ',updated_at:' },
  '0I no fallback before migration':   { file: '_upsert.js', from: "if(!/PGRST204|Could not find the '[^']*' column/i.test(String(e && e.message || e))) throw e;", to: 'throw e;' },
  '0I engine closes as nobody':        { file: '_engine.js', from: '{status:"dismissed",done_at:new Date().toISOString(),completed_by:"system"}', to: '{status:"dismissed",done_at:new Date().toISOString()}' },
  '0I dismissals counted as done':     { file: 'rep-usage-api.js', from: 't.status==="done" && t.done_at && t.done_at>=D.since &&', to: 't.done_at &&' },
  '0I credit goes to the assignee':    { file: 'rep-usage-api.js', from: '(t.completed_by ? isMine(k, t.completed_by) : isMine(k, t.assigned_email, t.assigned_rep))).length;', to: 'isMine(k, t.assigned_email, t.assigned_rep)).length;' },
  '0I record check needs new columns': { file: '_scope.js', from: 'const opt=new Set(opts.optional||[]); const base=cols.filter(c=>!opt.has(c));', to: 'const base=cols;' },
  '0J board ignores email owner':      { file: 'pipeline-api.js', from: '(!!myEmail && String(o.owner_email||"").toLowerCase()===myEmail) || ', to: '' },
  '0J new deal without email':         { file: 'pipeline-api.js', from: 'if(!manages || !clean(b.owner_rep,120)) row.owner_email=String(me.email||"").toLowerCase()||null;', to: '' },
  '0J update ignores email owner':     { file: 'pipeline-api.js', from: '{ownerFields:["owner_rep","owner_email"],optional:["owner_email"]}', to: '{ownerFields:["owner_rep"]}' },
  '0I badge counts by name only':      { file: 'crm-api.js', from: 'const n=(await repTasks(me,"open","id,assigned_rep,assigned_email")).length;', to: 'const n=((await sbGet(`dealer_tasks?status=eq.open&select=assigned_rep`).catch(()=>[]))||[]).filter(t=>String(t.assigned_rep||"").toLowerCase()===String(me.rep_name||"").toLowerCase()).length;' },
  // ---- Phase 0K: Relations = every dealer, no management powers ----
  '0K c360: Relations own book only':  { file: 'command360-api.js', from: 'if(ADMIN || RELATIONS){', to: 'if(ADMIN){' },
  '0K c360: Relations sees email review':{ file: 'command360-api.js', from: 'if(RELATIONS) emUn=[];', to: '' },
  '0K marketing: Relations own book':  { file: 'marketing-api.js', from: 'const all=SC.seesAllDealers(me);', to: 'const all=me.role==="president";' },
  '0K insights: team results to Relations':{ file: 'call-brief-api.js', from: 'by_rep: isAdmin(me) ?', to: 'by_rep: seesAllDealers(me) ?' },
  // ---- Phase 0L: one landing rule, off by default ----
  '0L management sent to rep home':    { file: 'staff-auth.js', from: 'if(["president","admin","owner"].includes(role)) return "/admin/";', to: '' },
  '0L off-site landing accepted':      { file: 'staff-auth.js', from: '&& /^\\/admin\\/[A-Za-z0-9._\\/-]*$/.test(cfg.url) && !cfg.url.includes(".."))', to: ')' },
  '0L pilot ignores the list':         { file: 'staff-auth.js', from: 'if(url && mode==="pilot" && listed) return url;', to: 'if(url && mode==="pilot") return url;' },
  '0L "off" behaves as "on"':          { file: 'staff-auth.js', from: 'if(url && mode==="on") return url;', to: 'if(url) return url;' },
  '0L Relations moved too':            { file: 'staff-auth.js', from: 'if(role==="relations") return (url && (mode==="pilot" || mode==="on") && listed) ? url : REP_HOME;', to: '' },
  // ---- Oct 2 decisions: Relations reads the Dealer Manager; the Admin dashboard is management's ----
  '0K non-management may write Dealer Manager':{ file: 'dealers-api.js', from: 'if(!isAdminRole && !NON_MGMT_READS.has(act)) return json(403,', to: 'if(role==="relations" && !NON_MGMT_READS.has(act)) return json(403,' },
  '0K Relations may write Dealer Manager':{ file: 'dealers-api.js', from: 'if(!isAdminRole && !NON_MGMT_READS.has(act)) return json(403,', to: 'if(role==="rep" && !NON_MGMT_READS.has(act)) return json(403,' },
  '0K non-management blocked from reads':{ file: 'dealers-api.js', from: 'const NON_MGMT_READS=new Set(["portal_access","preview_link"]);', to: 'const NON_MGMT_READS=new Set([]);' },
  '1A account numbers by anyone':      { file: 'crm-api.js', from: 'if(!isAdmin(me)) return json(403,{error:"Account numbers are changed by management."});', to: '' },
  '1A D360 account inputs to everyone':{ file: 'dealer.html', from: '${isMgmt()?`<input id="acct_', to: '${true?`<input id="acct_' },
  '0K Relations edit controls shown':  { file: 'dealers.html', from: 'const ro=isRelations();', to: 'const ro=false;' },
  '0K Relations verify link shown':    { file: 'dealers.html', from: 'pending verification</span>${isRelations()?"":', to: 'pending verification</span>${false?"":' },
  '0K D360 company edit to non-management':{ file: 'dealer.html', from: '${!isMgmt()?"":`<button class="btn ghost sm" onclick="editCompany()">', to: '${false?"":`<button class="btn ghost sm" onclick="editCompany()">' },
  '0K D360 isMgmt includes relations':{ file: 'dealer.html', from: '({president:1,admin:1,owner:1})[String(ME.role||"").toLowerCase()]', to: '({president:1,admin:1,owner:1,relations:1,rep:1})[String(ME.role||"").toLowerCase()]' },
  '0L Relations stays on Admin dash':  { file: 'index.html', from: 'if(role!=="rep"&&role!=="relations") return null;', to: 'if(role!=="rep") return null;' },
  '0L management sent off Admin dash': { file: 'index.html', from: 'if(role!=="rep"&&role!=="relations") return null;', to: 'if(!role) return null;' },
  '0F replay compared by key order':   { file: 'routes-api.js', from: 'canonJson(l.fields||{})===want', to: 'JSON.stringify(l.fields||{})===JSON.stringify(fields)' },
  '0F replay checks only the last visit':{ file: 'routes-api.js', from: 'const same=(done||[]).find(l=>l && l.completed_at && canonJson(l.fields||{})===want); if(same) prev=same;', to: 'const l=(done||[])[0]; if(l && l.completed_at && canonJson(l.fields||{})===want) prev=l;' },
  '0F replay window removed':          { file: 'routes-api.js', from: '&completed_at=gte.${encodeURIComponent(since)}', to: '' },
  // ---- Phase 1: visit lifecycle, meeting intelligence, follow-up, Dealer 360, Command Center ----
  '1 End ignores the time it was tapped':{ file: 'routes-api.js', from: 'const endIso=VI.clientTime(b.at,nowMs)||nowIso;', to: 'const endIso=nowIso;' },
  '1 a future client time is believed': { file: '_visits.js', from: 'if(t > now + 2 * 60000 || t < now - 36 * 3600000) return null;', to: 'if(t < now - 36 * 3600000) return null;' },
  '1 approval completes every time':    { file: 'routes-api.js', from: 'dealer_visit_reports?id=eq.${encodeURIComponent(reportId)}&completed_at=is.null&select=id', to: 'dealer_visit_reports?id=eq.${encodeURIComponent(reportId)}&select=id' },
  '1 any approval may create contacts': { file: 'routes-api.js', from: 'if(!cid && p.add_as_contact && (owned.has(k)||stale)){', to: 'if(!cid && p.add_as_contact){' },
  '1 tasks lose their origin key':      { file: '_tasks.js', from: 'row.origin_key = key && KEY_RE.test(key) ? key : null;', to: 'row.origin_key = null;' },
  '1 deals lose their origin key':      { file: '_opps.js', from: 'origin_key: key && KEY_RE.test(key) ? key : null,', to: 'origin_key: null,' },
  '1 a visit may create a won deal':    { file: '_opps.js', from: 'const stage = OPEN_STAGES.includes(', to: 'const stage = STAGES.includes(' },
  '1 approved stage not checked':       { file: 'routes-api.js', from: 'stage:OPP.OPEN_STAGES.includes(String(o.stage||"").toLowerCase())?String(o.stage).toLowerCase():"identified",', to: 'stage:String(o.stage||"identified").toLowerCase(),' },
  '1 empty analyze rewrites the notes': { file: 'routes-api.js', from: 'if(!empty){ try{ await sbSend("PATCH"', to: 'if(true){ try{ await sbSend("PATCH"' },
  '1 empty analyze calls the AI':       { file: 'routes-api.js', from: 'if(empty) return json(200,Object.assign({ok:false,report_id:r.id,error:"no_notes"', to: 'if(false) return json(200,Object.assign({ok:false,report_id:r.id,error:"no_notes"' },
  '1 email save marks it sent':         { file: 'routes-api.js', from: 'sent_at:b.sent?new Date().toISOString():(prev.sent_at||null)', to: 'sent_at:new Date().toISOString()' },
  '1 email drafted before approval':    { file: 'ai-email-api.js', from: 'if(!v.approved_at) return json(400,{error:"Approve the visit summary first."});', to: '' },
  "1 email from another dealer's visit":{ file: 'ai-email-api.js', from: 'if(!v || String(v.dealer_id)!==dealerId) return json(404,', to: 'if(!v) return json(404,' },
  '1 a deal never holds follow-up':     { file: '_visits.js', from: 'const openO = O.filter(o => o.status === "open" && String(o.stage) === String(approvedStage[o.origin_key] || "identified"));', to: 'const openO = [];' },
  '1 follow-up filter misses null':     { file: '_visits.js', from: '&followup_manual=not.is.true`', to: '&followup_manual=eq.false`' },
  '1 D360 attendee name not kept':      { file: 'crm-api.js', from: 'map(p=>({name:p.name_snapshot,', to: 'map(p=>({name:p.contact_id,' },
  '1 CC: a rep may pick anyone':        { file: 'rep-command-api.js', from: 'if(b.rep && canPick && low(b.rep)!==who.email){', to: 'if(b.rep && low(b.rep)!==who.email){' },
  '1 CC: rep list offered to reps':     { file: 'rep-command-api.js', from: 'if(!canPick) return json(200,{ok:true,reps:[]});', to: '' },
  '1 CC: tasks first page only':        { file: 'rep-command-api.js', from: 'getAll(`dealer_tasks?status=eq.open&or=(${mineTasks})&select=', to: 'sbGet(`dealer_tasks?status=eq.open&or=(${mineTasks})&select=' },
  "1 CC: another rep's route shown":    { file: 'rep-command-api.js', from: 'const mineRoutes=(routes||[]).filter(r=>r.assigned_to_email ? low(r.assigned_to_email)===who.email : low(r.owner_email)===who.email);', to: 'const mineRoutes=(routes||[]);' },
  // ---- Phase 1 blocker fixes ----
  '1F AI: no automatic retry':          { file: '_visit_ai.js', from: 'if(!res.ok && res.retry && left >= minRetry){', to: 'if(false){' },
  '1F AI: old output allowance':        { file: '_visit_ai.js', from: 'const MAX_TOKENS = 4096;', to: 'const MAX_TOKENS = 1800;' },
  '1F AI: shape not validated':         { file: '_visit_ai.js', from: '  if(!validRaw(raw, i.part)) return { ok: false, error: "ai_invalid"', to: '  if(false) return { ok: false, error: "ai_invalid"' },
  '1F AI: naive JSON parse':            { file: '_visit_ai.js', from: 'const t = String(text == null ? "" : text).replace(/```(?:json)?/gi, "");', to: 'const t = String(text == null ? "" : text); { const a = t.indexOf("{"), b = t.lastIndexOf("}"); try{ return JSON.parse(t.slice(a, b + 1)); }catch(_){ return null; } }' },
  '1F AI: retries without limit':       { file: '_visit_ai.js', from: '      attempts = 2;\n    }', to: '      attempts = 2;\n      if(!res.ok) res = await callOnce(p, 5000), attempts = 3;\n    }' },
  '1F AI: one part failing fails all':  { file: '_visit_ai.js', from: 'if(meeting && !meeting.ok) return { ok: false', to: 'if(meeting && (!meeting.ok || !(results.followups || {}).ok)) return { ok: false' },
  '1F AI: stray follow-ups from summary half':{ file: '_visit_ai.js', from: 'if(!ACTION_KEYS.includes(k)) raw[k] = v;', to: 'raw[k] = v;' },
  '1F AI: later parts overwrite others':{ file: '_visit_ai.js', from: 'if(res && res.ok) for(const k of PART_KEYS[part]) if(res.raw[k] != null) raw[k] = res.raw[k];', to: 'if(res && res.ok) Object.assign(raw, res.raw);' },
  '1F AI: summary part not required':   { file: '_visit_ai.js', from: 'if((!part || part === "meeting") && (typeof raw.meeting_summary', to: 'if(false && (typeof raw.meeting_summary' },
  '1F AI: missing deals not flagged':   { file: '_visit_ai.js', from: 'const missing = want.filter(p => p !== "meeting" && !results[p].ok)', to: 'const missing = want.filter(p => p !== "meeting" && p !== "deals" && !results[p].ok)' },
  '1F AI: deals asked in the follow-ups part':{ file: '_visit_ai.js', from: 'i.part === "followups" ? FOLLOWUPS_SPEC(i) :', to: 'i.part === "followups" ? FOLLOWUPS_SPEC(i) + DEALS_SPEC :' },
  '1F AI: partial not flagged':         { file: 'routes-api.js', from: 'model:VISIT_AI_MODEL,partial:partial||undefined});', to: 'model:VISIT_AI_MODEL});' },
  '1F AI: partial served from cache':   { file: 'routes-api.js', from: ' && !r.ai_suggestion.partial)', to: ')' },
  '1F AI: partial offers no retry':     { file: 'scheduled-routes.html', from: 'return REV && (REV.manual||REV.partial) && ', to: 'return REV && REV.manual && ' },
  '1F QA retry switch for anyone':      { file: 'routes-api.js', from: 'const qaFail=b.qa_fail_first===true && qaOk;', to: 'const qaFail=b.qa_fail_first===true;' },
  '1K email: thinking left on':         { file: 'ai-email-api.js', from: 'let r=await send({type:"disabled"})', to: 'let r=await send(null)' },
  '1K AI: thinking left on':             { file: '_visit_ai.js', from: 'r = await send(NO_THINKING);', to: 'r = await send(null);' },
  '1K AI: no fallback without thinking':{ file: '_visit_ai.js', from: 'if(r.status === 400 && /thinking/i.test(t)){', to: 'if(false){' },
  '1K check: numbers run into the next product':{ file: '_visit_ai.js', from: '["and", "or", "plus", "vs", "versus"].includes(la)) break;', to: 'false) break;' },
  '1K check: counts of models read as units':{ file: '_visit_ai.js', from: 'if(after.some(a => COUNTS_OTHER.has(', to: 'if(false && after.some(a => COUNTS_OTHER.has(' },
  '1J QA part failure for anyone':      { file: 'routes-api.js', from: 'const qaParts=qaOk ?', to: 'const qaParts=true ?' },
  '1J forced part still calls the AI':  { file: '_visit_ai.js', from: 'if(forceFail.has(part)) return {', to: 'if(false) return {' },
  '1J check: quantity ignored':         { file: '_visit_ai.js', from: 'if(hit) flag(o, "quantity"', to: 'if(false) flag(o, "quantity"' },
  '1J check: conflict resolved silently':{ file: '_visit_ai.js', from: 'if(hit) flag(o, "quantity"', to: 'if(hit) o.quantity = hit.n, flag(o, "quantity"' },
  '1J check: model not against notes':  { file: '_visit_ai.js', from: 'const firstBad = s => modelCodes(s).find(c => !inNotes(c.digits));', to: 'const firstBad = s => undefined;' },
  '1J check: deal contact unchecked':   { file: '_visit_ai.js', from: 'if(people.some(p => p === k || p.split(" ")[0] === first)) continue;', to: 'continue;' },
  '1J check: promised date unchecked':  { file: '_visit_ai.js', from: 'if(c) flag(f, "date"', to: 'if(false) flag(f, "date"' },
  '1J check: next-action date unchecked':{ file: '_visit_ai.js', from: 'if(f) flag(na, "date"', to: 'if(false) flag(na, "date"' },
  '1J check: requests unchecked':       { file: '_visit_ai.js', from: 'checks.push({ kind: "request"', to: 'void({ kind: "request"' },
  '1J check: other deal not considered':{ file: '_visit_ai.js', from: 'if(opps.some(p => p !== o && p.quantity === q.n', to: 'if(false && opps.some(p => p !== o && p.quantity === q.n' },
  '1J check: not run on the server':    { file: 'routes-api.js', from: 'VAI.crossCheck(sug,{notes,transcript,mfrs,contacts:contacts||[]});', to: '' },
  '1J retry asks every part again':     { file: 'routes-api.js', from: 'only:merge?retryParts:undefined', to: 'only:undefined' },
  '1J retry replaces kept sections':    { file: '_visit_ai.js', from: 'for(const part of parts) for(const k of PART_KEYS[part]) out[k] = fresh[k];', to: 'Object.assign(out, fresh);' },
  '1J retry merges stale notes':        { file: 'routes-api.js', from: '&& stored.input_hash===inputHash &&', to: '&&' },
  '1J partial kept after retry':        { file: 'routes-api.js', from: 'for(const p of back) still.delete(VAI.SECTION[p]);', to: '' },
  '1J retry fills only what came back': { file: 'routes-api.js', from: 'const back=retryParts.filter(p=>res.parts[p]&&res.parts[p].ok);', to: 'const back=retryParts;' },
  '1J partial note names nothing':      { file: 'scheduled-routes.html', from: 'REV.partial=true; REV.missing=miss;', to: 'REV.partial=true; REV.missing=[];' },
  '1F repeated follow-up ticked':       { file: '_visit_ai.js', from: 'if(twin){ item.dup_of = twin.key; item.dup_title = twin.title; }', to: '' },
  '1F repeated next action ticked':     { file: '_visit_ai.js', from: 'if(next.text){ const twin', to: 'if(false){ const twin' },
  '1F dates ignored in repeats':        { file: '_visit_ai.js', from: 'if(!ignoreDates && da && db && da !== db) return false;', to: '' },
  '1G visit for a dealer that does not exist':{ file: 'routes-api.js', from: 'if(!ex) return json(404,{error:"Dealer not found."});', to: '' },
  '1H email: no visit date':            { file: 'ai-email-api.js', from: 'recap=(visitDay?`Visit date: ${visitDay.long} (the meeting was in person)\\n`:"")+visitRecapLines(v);', to: 'recap=visitRecapLines(v);' },
  '1H email: relative days left in':    { file: 'ai-email-api.js', from: 'subject=fixRelativePast(subject,visitDay.md); body=fixRelativePast(body,visitDay.md);', to: '' },
  '1H email: no rewrite asked for':     { file: 'ai-email-api.js', from: 'if(visitDay && RELATIVE_DAY.test(`${g.subject}\\n${g.body}`)){', to: 'if(false){' },
  '1H email: QA date on a real dealer': { file: 'ai-email-api.js', from: 'if(dt&&dt[0]&&dt[0].is_test===true && Number.isFinite', to: 'if(Number.isFinite' },
  '1H email: greets someone before a pick': { file: 'ai-email-api.js', from: 'if(recap && !firstName) body=neutralGreeting(body);', to: '' },
  // ("one attendee → that attendee" also follows from attendees being listed first, so a mutant of that branch is equivalent.)
  // ---- My Sales Workspace (President dual role) + Relations Command Center landing ----
  '1W listed Relations ignored':       { file: 'staff-auth.js', from: '(url && (mode==="pilot" || mode==="on") && listed)', to: '(false)' },
  '1W Relations moves while "off"':    { file: 'staff-auth.js', from: '(url && (mode==="pilot" || mode==="on") && listed)', to: '(url && listed)' },
  '1W Relations never reaches the pilot':{ file: 'staff-auth.js', from: '(role!=="rep" && role!=="relations")) return REP_HOME;', to: 'role!=="rep") return REP_HOME;' },
  '1W pilot list case-sensitive':      { file: 'staff-auth.js', from: 'cfg.emails.map(e=>String(e||"").trim().toLowerCase()).includes(me)', to: 'cfg.emails.includes(me)' },
  '1W header honored for any role':    { file: '_scope.js', from: 'return low(v)==="mine" && isAdmin(me);', to: 'return low(v)==="mine";' },
  '1W header ignored':                 { file: '_scope.js', from: 'return low(v)==="mine" && isAdmin(me);', to: 'return false;' },
  '1W header any value':               { file: '_scope.js', from: 'return low(v)==="mine" && isAdmin(me);', to: 'return !!v && isAdmin(me);' },
  '1W book resolved as President':     { file: '_scope.js', from: 'return dealerScope(Object.assign({}, me, {role:"rep"}), sbGet, idx);', to: 'return dealerScope(me, sbGet, idx);' },
  '1W CC picker kept in workspace':    { file: 'rep-command-api.js', from: 'const canPick=SC.seesAllDealers(me) && !workspace;', to: 'const canPick=SC.seesAllDealers(me);' },
  '1W CC narrows Relations':           { file: 'rep-command-api.js', from: 'const canPick=SC.seesAllDealers(me) && !workspace;', to: 'const canPick=SC.seesAllDealers(me) && !SC.workspaceMine({headers:{"x-hcps-workspace":"mine"}},{role:"president"});' },
  '1W tasks company-wide in workspace':{ file: 'crm-api.js', from: 'const seesAll=seesAllDealers(me) && !SC.workspaceMine(event, me);', to: 'const seesAll=seesAllDealers(me);' },
  '1W task badge company-wide':        { file: 'crm-api.js', from: 'if(seesAllDealers(me) && !SC.workspaceMine(event, me)){   // in My', to: 'if(seesAllDealers(me)){   // in My' },
  '1W pipeline company-wide':          { file: 'pipeline-api.js', from: 'const isRep = workspace ||', to: 'const isRep =' },
  '1W pipeline book as President':     { file: 'pipeline-api.js', from: '(workspace ? SC.ownBook(me, sbGet, OI||undefined) :', to: '(workspace ? SC.dealerScope(me, sbGet, OI||undefined) :' },
  '1W routes planned for others kept': { file: 'routes-api.js', from: 'if(workspace) rows=(rows||[]).filter(', to: 'if(false) rows=(rows||[]).filter(' },
  '1W routes company-wide':            { file: 'routes-api.js', from: 'const workspace=SC.workspaceMine(event, me);\n      if(!isBoss(me) || workspace)', to: 'const workspace=false;\n      if(!isBoss(me) || workspace)' },
  '1W dealer list company-wide':       { file: 'dealers-api.js', from: '} else if(SC.workspaceMine(event, me)){', to: '} else if(false){' },
  '1W map company-wide':               { file: 'geocode-api.js', from: 'if(SC.workspaceMine(event, me)){', to: 'if(false){' },
  '1I recipient: picks for the rep':    { file: 'scheduled-routes.html', from: 'else if(attRows.length>1){ note=', to: 'else if(attRows.length>1){ pre.add(low(attRows[0].email)); note=' },
};
