-- LOCAL TEST FIXTURE ONLY — approximates the live shape of the tables MI-1a touches.
-- Never run against production.
do $$ begin create role anon; create role authenticated; create role service_role bypassrls; exception when duplicate_object then null; end $$;
alter role service_role bypassrls;   -- as on Supabase: the service role is not subject to RLS
-- As on Supabase's API: every session loads pg-safeupdate (authenticator role:
-- session_preload_libraries = supautils, safeupdate), which refuses UPDATE / DELETE without a WHERE clause —
-- including inside functions and on temp tables. Found live 2026-10-10 (hcps_sales_report_apply preview).
do $$ begin execute format('alter database %I set session_preload_libraries = %L', current_database(), 'safeupdate'); end $$;
-- Like Supabase: every new table / sequence in public is granted to anon, authenticated and service_role by default.
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
create extension if not exists pgcrypto;
create table manufacturers(slug text primary key, name text);
insert into manufacturers values ('strongback-mobility','Strongback Mobility'),('pedifix','PediFix'),('ovation-medical','Ovation Medical');
create table dealers(id uuid primary key default gen_random_uuid(), business_name text, parent_id uuid, city text, state text, zip text);
create table monthly_sales(
  id bigint generated by default as identity primary key,
  dealer_id uuid references dealers(id),
  manufacturer text references manufacturers(slug),
  period date, amount numeric, qty numeric, product_code text, product_name text, hcps_account text,
  rep_id uuid, cost numeric, commission numeric, customer_name text, customer_ref text, rep_name text,
  ship_city text, ship_state text, ship_zip text, ship_name text, ship_address text,
  order_date date, channel text, item_no text, line_type text, credit_reason text, invoice_no text,
  commission_rate numeric, billed_amount numeric, memo text,
  source text, external_ref text, source_file text, imported_at timestamptz);
create unique index monthly_sales_extref_uniq on monthly_sales(manufacturer, external_ref);

-- Dealers
insert into dealers(id,business_name,city,state,zip) values
 ('00000000-0000-0000-0000-00000000000a','Williams Brothers Washington HQ','Washington','IN','47501'),
 ('00000000-0000-0000-0000-00000000000b','Scenic City Medical Equipment','Chattanooga','TN','37416');
insert into dealers(id,business_name,parent_id,city,state,zip) values
 ('00000000-0000-0000-0000-00000000000c','Williams Brothers Vincennes','00000000-0000-0000-0000-00000000000a','Vincennes','IN','47591');

-- Strongback sales_report rows imported the OLD way (row-index keys), incl. the hazards:
--  * order 6491: two identical lines (repeated line) + one other SKU
--  * order 6854: imported twice from two exports in a different row order (a real duplicate)
--  * order 7001: branch-attributed to Vincennes by hand
--  * a $0 collateral line, a credit line, and a line with no order number
insert into monthly_sales(dealer_id,manufacturer,period,order_date,invoice_no,product_code,product_name,qty,amount,commission,commission_rate,customer_name,source,external_ref,source_file,imported_at,line_type,rep_name) values
 ('00000000-0000-0000-0000-00000000000a','strongback-mobility','2026-04-01','2026-04-15','6491','1010-2025','Comfort 24',1,536,48.24,0.09,'Williams Brothers','sales_report','strongback-mobility|6491|1010-2025|0','ytd-may.xlsx','2026-05-02','sale','Angelo Audia'),
 ('00000000-0000-0000-0000-00000000000a','strongback-mobility','2026-04-01','2026-04-15','6491','1010-2025','Comfort 24',1,536,48.24,0.09,'Williams Brothers','sales_report','strongback-mobility|6491|1010-2025|1','ytd-may.xlsx','2026-05-02','sale','Angelo Audia'),
 ('00000000-0000-0000-0000-00000000000a','strongback-mobility','2026-04-01','2026-04-15','6491','Brochure Trifold','Brochure Trifold',1,0,0,0.09,'Williams Brothers','sales_report','strongback-mobility|6491|Brochure Trifold|2','ytd-may.xlsx','2026-05-02','collateral','Angelo Audia'),
 ('00000000-0000-0000-0000-00000000000a','strongback-mobility','2026-07-01','2026-07-02','6854','ES0001','ErgoSteel',2,880,79.20,0.09,'Williams Brothers','sales_report','strongback-mobility|6854|ES0001|3','ytd-jul.xlsx','2026-08-03','sale','Angelo Audia'),
 ('00000000-0000-0000-0000-00000000000a','strongback-mobility','2026-07-01','2026-07-02','6854','ES0001','ErgoSteel',2,880,79.20,0.09,'Williams Brothers','sales_report','strongback-mobility|6854|ES0001|7','ytd-jul-v2.xlsx','2026-08-05','sale','Angelo Audia'),
 ('00000000-0000-0000-0000-00000000000c','strongback-mobility','2026-07-01','2026-07-09','7001','1007-2025','Comfort M',1,536,48.24,0.09,'Williams Brothers','sales_report','strongback-mobility|7001|1007-2025|4','ytd-jul.xlsx','2026-08-03','sale','Angelo Audia'),
 ('00000000-0000-0000-0000-00000000000b','strongback-mobility','2026-01-01','2026-01-15','5794','1010-2025','Comfort 24',1,-65,-5.85,0.09,'Medical Supply Store','sales_report','strongback-mobility|5794|1010-2025|5','ytd-jan.xlsx','2026-02-01','collateral','Angelo Audia'),
 (null,'strongback-mobility','2025-10-01','2025-10-20',null,'R0001','SEATA rollator',1,299,26.91,0.09,'GF Health Products Inc','sales_report','strongback-mobility|na|R0001|6','ytd-oct.xlsx','2025-11-01','sale',null);
-- A commission-lane row and a legacy (no source) row on another manufacturer, which MI-1a must never touch.
insert into monthly_sales(dealer_id,manufacturer,period,amount,commission,customer_name,source,source_file) values
 ('00000000-0000-0000-0000-00000000000b','pedifix','2026-07-01',100,10,'Scenic City','commission','pedifix-jul.csv'),
 ('00000000-0000-0000-0000-00000000000b','pedifix','2026-06-01',50,5,'Scenic City',null,null);

-- Historical (pre-MI-1a) Ovation commission statement for July 2026: 3 lines, no batch record.
insert into monthly_sales(dealer_id,manufacturer,period,amount,commission,customer_name,invoice_no,product_code,qty,source,source_file,imported_at) values
 ('00000000-0000-0000-0000-00000000000b','ovation-medical','2026-07-01',200,20,'Scenic City','INV-1','4900-WRAP',10,'commission','ovation-jul.xlsx','2026-08-10'),
 ('00000000-0000-0000-0000-00000000000a','ovation-medical','2026-07-01',300,30,'Williams Brothers','INV-2','GEN2-TALL',2,'commission','ovation-jul.xlsx','2026-08-10'),
 ('00000000-0000-0000-0000-00000000000a','ovation-medical','2026-07-01',100,10,'Williams Brothers','INV-3','GEN2-SHORT',1,'commission','ovation-jul.xlsx','2026-08-10');
-- Strongback customer refs (account usernames) on two orders, for the collision checks.
update monthly_sales set customer_ref='wbhcp' where manufacturer='strongback-mobility' and invoice_no in ('6491','7001');
